steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-service/app:$COMMIT_SHA'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-service/app:latest'
      - '.'

  # Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '--all-tags'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-service/app'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - portfolio-service
      - '--image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-service/app:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--quiet'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-service/app'

options:
  logging: CLOUD_LOGGING_ONLY
